services:
  backend:
    build: ./backend
    container_name: inventario_api
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: inventario_ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
